### ISSUE TITLE
Attribution isn't clickable

### ISSUE THREAD

**Issue by KathleenLD** [mapzen/poipond#2]
In both Chrome and FF on an Ubuntu system I'm not able to click the Mapbox/OSM attribution icon. 

When I click on that I would expect to see the OSM attribution along w/ Mapbox's attribution. 

According to @mjcunningham it's clickable on the "Get Started" page, but once you dig in the POI/fish container is floating over it. 

/cc @souperneon

**Comment by souperneon** [comment]
Mapzen map now!
